name: Deploy Astro to Server

on:
  push:
    branches:
      - main # Или master, в зависимости от вашей основной ветки

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to server
        uses: appleboy/scp-action
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "dist/*" # Что копируем. `dist/*` — содержимое папки `dist`
          target: ${{ secrets.DEPLOY_TARGET_PATH }} # Куда копируем
          strip_components: 1 # Убирает папку `dist` из пути назначения, копируя только ее содержимое